import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# GPU Accelerated Matrix Factorization (cu2rec)\n",
    "Implementing the parallel SGD algorithm with **Early Bird Gets the Gradient (EBGTG)** using `numba.cuda`.\n",
    "\n",
    "Paper: *GPU Accelerated Matrix Factorization for Recommender Systems* (Kilitcioglu et al., 2021)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Mount Google Drive to access u.data\n",
    "from google.colab import drive\n",
    "drive.mount('/content/drive')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import math\n",
    "import time\n",
    "from numba import cuda\n",
    "from scipy.sparse import csr_matrix"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ===== Data Loading & Preprocessing =====\n",
    "DATA_PATH = '/content/drive/MyDrive/gpu programming/gpu_last_time/u.data'\n",
    "\n",
    "df = pd.read_csv(DATA_PATH, sep='\\t', names=['user', 'item', 'rating', 'timestamp'])\n",
    "# Convert 1-indexed IDs to 0-indexed\n",
    "df['user'] = df['user'] - 1\n",
    "df['item'] = df['item'] - 1\n",
    "\n",
    "num_users = df['user'].max() + 1\n",
    "num_items = df['item'].max() + 1\n",
    "num_ratings = len(df)\n",
    "\n",
    "print(f'Users: {num_users}, Items: {num_items}, Ratings: {num_ratings}')\n",
    "\n",
    "# Global bias (mean of all ratings)\n",
    "global_bias = df['rating'].mean()\n",
    "print(f'Global Bias (mu): {global_bias:.4f}')\n",
    "\n",
    "# Build CSR (Compressed Sparse Row) matrix\n",
    "ratings_csr = csr_matrix(\n",
    "    (df['rating'].values, (df['user'].values, df['item'].values)),\n",
    "    shape=(num_users, num_items)\n",
    ")\n",
    "\n",
    "indptr  = np.array(ratings_csr.indptr,  dtype=np.int32)\n",
    "indices = np.array(ratings_csr.indices, dtype=np.int32)\n",
    "data    = np.array(ratings_csr.data,    dtype=np.float32)\n",
    "\n",
    "print(f'CSR matrix built: indptr={indptr.shape}, indices={indices.shape}, data={data.shape}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ===== Hyperparameters (from paper Section IV) =====\n",
    "f = 50                        # number of latent factors\n",
    "alpha = np.float32(0.01)      # learning rate (eta)\n",
    "reg_p = np.float32(0.02)      # lambda_p (P regularization)\n",
    "reg_q = np.float32(0.02)      # lambda_q (Q regularization)\n",
    "reg_u = np.float32(0.02)      # lambda_u (user bias regularization)\n",
    "reg_i = np.float32(0.02)      # lambda_i (item bias regularization)\n",
    "total_iterations = 5000       # training iterations\n",
    "\n",
    "print(f'Factors: {f}, LR: {alpha}, Regularization: {reg_p}')\n",
    "print(f'Total iterations: {total_iterations}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ===== CUDA Kernels =====\n",
    "\n",
    "# Device function: Equation (1) from paper\n",
    "# R_hat_ui = mu + U_u + I_i + Q_i^T * P_u\n",
    "@cuda.jit(device=True)\n",
    "def get_prediction(P, Q, user_bias, item_bias, gb, u, i, f):\n",
    "    pred = gb + user_bias[u] + item_bias[i]\n",
    "    for k in range(f):\n",
    "        pred += P[u, k] * Q[i, k]\n",
    "    return pred\n",
    "\n",
    "\n",
    "# SGD Kernel: Algorithm 1 from paper\n",
    "# Implements Early Bird Gets the Gradient (EBGTG)\n",
    "# with User Index Striding for fairness\n",
    "@cuda.jit\n",
    "def sgd_kernel(indptr, indices, data, P, Q, user_bias, item_bias,\n",
    "               gb, item_updated, f, alpha, reg_p, reg_q, reg_u, reg_i,\n",
    "               start_user, num_users, seed_states):\n",
    "    # Line 2 of Algorithm 1: x = (blockDim.x * blockIdx.x + threadIdx.x + startUser) % nRows\n",
    "    tid = cuda.blockIdx.x * cuda.blockDim.x + cuda.threadIdx.x\n",
    "    if tid >= num_users:\n",
    "        return\n",
    "\n",
    "    u = (tid + start_user) % num_users   # User index striding\n",
    "    low  = indptr[u]\n",
    "    high = indptr[u + 1]\n",
    "\n",
    "    if low == high:  # User has no ratings\n",
    "        return\n",
    "\n",
    "    # --- Random item selection (Xorshift32 PRNG) ---\n",
    "    state = seed_states[tid]\n",
    "    state ^= (state << 13)\n",
    "    state ^= (state >> 17)\n",
    "    state ^= (state << 5)\n",
    "    if state == 0:\n",
    "        state = 1\n",
    "    seed_states[tid] = state\n",
    "\n",
    "    # Line 4: yi = RANDOM_ITEM(x)\n",
    "    num_items_for_user = high - low\n",
    "    yi = low + (state % num_items_for_user)\n",
    "\n",
    "    # Line 6-8: y, ub, ib\n",
    "    y  = indices[yi]\n",
    "    ub = user_bias[u]\n",
    "    ib = item_bias[y]\n",
    "\n",
    "    # Line 10-11: pred, error (Equations 1 & 2)\n",
    "    pred  = get_prediction(P, Q, user_bias, item_bias, gb, u, y, f)\n",
    "    error = data[yi] - pred\n",
    "\n",
    "    # Line 13-14: EBGTG check\n",
    "    early_bird = not item_updated[y]\n",
    "    item_updated[y] = True\n",
    "\n",
    "    # Line 16-27: Update P and Q feature vectors (Equations 6 & 7)\n",
    "    for k in range(f):\n",
    "        p_old = P[u, k]\n",
    "        q_old = Q[y, k]\n",
    "        # Equation 6: P update (always done)\n",
    "        P[u, k] = p_old + alpha * (error * q_old - reg_p * p_old)\n",
    "        # Equation 7: Q update (only if early bird)\n",
    "        if early_bird:\n",
    "            Q[y, k] = q_old + alpha * (error * p_old - reg_q * q_old)\n",
    "\n",
    "    # Line 29: User bias update (Equation 8)\n",
    "    user_bias[u] = ub + alpha * (error - reg_u * ub)\n",
    "\n",
    "    # Line 31-33: Item bias update (Equation 9) - only if early bird\n",
    "    if early_bird:\n",
    "        item_bias[y] = ib + alpha * (error - reg_i * ib)\n",
    "\n",
    "\n",
    "# Loss Kernel: Algorithm 2 from paper\n",
    "# Computes squared error for all ratings of each user\n",
    "@cuda.jit\n",
    "def loss_kernel(indptr, indices, data, P, Q, user_bias, item_bias,\n",
    "                gb, num_users, f, losses):\n",
    "    u = cuda.blockIdx.x * cuda.blockDim.x + cuda.threadIdx.x\n",
    "    if u >= num_users:\n",
    "        return\n",
    "    start_idx = indptr[u]\n",
    "    end_idx   = indptr[u + 1]\n",
    "    user_loss = 0.0\n",
    "    for idx in range(start_idx, end_idx):\n",
    "        i = indices[idx]\n",
    "        rating = data[idx]\n",
    "        pred = get_prediction(P, Q, user_bias, item_bias, gb, u, i, f)\n",
    "        err  = rating - pred\n",
    "        user_loss += err * err\n",
    "    losses[u] = user_loss\n",
    "\n",
    "\n",
    "# Reset kernel: clears itemIsUpdated array before each iteration\n",
    "@cuda.jit\n",
    "def reset_kernel(item_updated, num_items):\n",
    "    i = cuda.blockIdx.x * cuda.blockDim.x + cuda.threadIdx.x\n",
    "    if i < num_items:\n",
    "        item_updated[i] = False\n",
    "\n",
    "print('CUDA kernels defined successfully!')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ===== Initialize & Transfer to GPU =====\n",
    "threads_per_block = 256\n",
    "blocks_users = (num_users + threads_per_block - 1) // threads_per_block\n",
    "blocks_items = (num_items + threads_per_block - 1) // threads_per_block\n",
    "\n",
    "np.random.seed(42)\n",
    "\n",
    "# P (m x f) and Q (n x f) initialized with N(0, 1/f) as per paper Section III-D\n",
    "P_host = np.random.normal(0, 1.0 / f, size=(num_users, f)).astype(np.float32)\n",
    "Q_host = np.random.normal(0, 1.0 / f, size=(num_items, f)).astype(np.float32)\n",
    "user_bias_host = np.zeros(num_users, dtype=np.float32)\n",
    "item_bias_host = np.zeros(num_items, dtype=np.float32)\n",
    "\n",
    "# Xorshift seed states (one per thread/user)\n",
    "seed_states_host = np.random.randint(1, 1_000_000, size=num_users).astype(np.int32)\n",
    "\n",
    "print('Copying data to GPU...')\n",
    "P_d  = cuda.to_device(P_host)\n",
    "Q_d  = cuda.to_device(Q_host)\n",
    "ub_d = cuda.to_device(user_bias_host)\n",
    "ib_d = cuda.to_device(item_bias_host)\n",
    "seeds_d = cuda.to_device(seed_states_host)\n",
    "losses_d = cuda.device_array(num_users, dtype=np.float32)\n",
    "item_updated_d = cuda.device_array(num_items, dtype=np.bool_)\n",
    "\n",
    "indptr_d  = cuda.to_device(indptr)\n",
    "indices_d = cuda.to_device(indices)\n",
    "data_d    = cuda.to_device(data)\n",
    "\n",
    "gb32 = np.float32(global_bias)\n",
    "print('GPU memory allocated and data transferred!')\n",
    "print(f'Grid config: {blocks_users} blocks x {threads_per_block} threads (users)')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ===== Training Loop =====\n",
    "print('='*60)\n",
    "print('Starting cu2rec GPU Training')\n",
    "print('='*60)\n",
    "\n",
    "offset = 0\n",
    "eval_interval = 500\n",
    "\n",
    "start_time = time.time()\n",
    "\n",
    "for iteration in range(1, total_iterations + 1):\n",
    "    # Reset itemIsUpdated array\n",
    "    reset_kernel[blocks_items, threads_per_block](item_updated_d, num_items)\n",
    "\n",
    "    # Run SGD kernel (Algorithm 1)\n",
    "    sgd_kernel[blocks_users, threads_per_block](\n",
    "        indptr_d, indices_d, data_d, P_d, Q_d, ub_d, ib_d,\n",
    "        gb32, item_updated_d, f, alpha, reg_p, reg_q, reg_u, reg_i,\n",
    "        offset, num_users, seeds_d\n",
    "    )\n",
    "\n",
    "    # User index striding (Section III-E-5)\n",
    "    offset = (offset + 97) % num_users\n",
    "\n",
    "    cuda.synchronize()\n",
    "\n",
    "    # Periodically compute RMSE (Equation 11)\n",
    "    if iteration % eval_interval == 0:\n",
    "        loss_kernel[blocks_users, threads_per_block](\n",
    "            indptr_d, indices_d, data_d, P_d, Q_d, ub_d, ib_d,\n",
    "            gb32, num_users, f, losses_d\n",
    "        )\n",
    "        cuda.synchronize()\n",
    "        total_loss = np.sum(losses_d.copy_to_host())\n",
    "        rmse = math.sqrt(total_loss / num_ratings)\n",
    "        elapsed = time.time() - start_time\n",
    "        print(f'Iter {iteration:5d}/{total_iterations} | RMSE: {rmse:.4f} | Time: {elapsed:.2f}s')\n",
    "\n",
    "total_time = time.time() - start_time\n",
    "print('='*60)\n",
    "print(f'Training completed in {total_time:.2f} seconds.')\n",
    "print(f'Final RMSE: {rmse:.4f}')\n",
    "print('='*60)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ===== Copy Results Back to Host =====\n",
    "P_final = P_d.copy_to_host()\n",
    "Q_final = Q_d.copy_to_host()\n",
    "user_bias_final = ub_d.copy_to_host()\n",
    "item_bias_final = ib_d.copy_to_host()\n",
    "\n",
    "print(f'P matrix shape: {P_final.shape}')\n",
    "print(f'Q matrix shape: {Q_final.shape}')\n",
    "print(f'User biases: {user_bias_final[:5]}')\n",
    "print(f'Item biases: {item_bias_final[:5]}')\n",
    "print(f'Global bias: {global_bias:.4f}')\n",
    "\n",
    "# Example prediction for user 0, item 0\n",
    "example_pred = global_bias + user_bias_final[0] + item_bias_final[0] + np.dot(P_final[0], Q_final[0])\n",
    "print(f'\\nExample prediction (user=0, item=0): {example_pred:.4f}')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open('g:/My Drive/gpu programming/gpu_last_time/practice_pd.ipynb', 'w') as f:
    json.dump(notebook, f, indent=1)
print("Notebook created successfully!")
